<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Berhasil melakukan Koreksi</name>
   <tag></tag>
   <elementGuidId>663d524f-dbcd-409d-b928-ac3253fa2055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>7b288ce2-a739-466e-8564-8ebbbbf53d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1740248235044</value>
      <webElementGuid>9e01607f-8f18-4285-83e0-6a9ad6ce3a80</webElementGuid>
   </webElementProperties>
</WebElementEntity>
